name: avance2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  provider: ^6.1.2
  intl: ^0.19.0
  flutter_speed_dial: ^7.0.0
  uuid: ^4.5.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1
  camera: ^0.10.5+2
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logotaller.jpeg
    - assets/tflite/
    - assets/tflite/mobilefacenet.tflite
    - assets/tflite/FaceAntiSpoofing.tflite
    - assets/tflite/background.jpg
    - assets/tflite/face.jpg
